### PR TITLE
Some upgrades

### PR DESCRIPTION
**Pull request by scrakcho**
Fix a problem with background image and flag icon.
Added support to no button label.
Language packs.

### CODE REVIEW

**Comment by scrakcho** [comment]
Last problem with names in the min.js solved

**Comment by josh18** [comment]
Thanks for the pull request. Sorry I haven't had a chance to check the commits yet but will merge when I get a chance to go through them.

**Comment by scrakcho** [comment]
I dont know, my problem was a strange background... and i added "background-image:none !important;".
imagen

**Comment by scrakcho** [comment]
Maybe its comming from tinymce skin that im using... its "lightgraynofonts"

**Comment by josh18** [comment]
Ah yup that makes sense. I've added the language support via 7094d6d972a167a8ff1ab4cbc543bf249f42a6dd, thanks for the help!

**Pull request closed without merging**
