### PR TITLE
Included search and removed noneditable dependency

### PR DESCRIPTION
**Pull request by csauthoff**
- The dependency from the „noneditable“ plugin is removed, thus icons
can be resized, changed, etc.

- Icons will be saved as i-tags, providing cleaner markup.

- Implemented a search feature.

- Improved UI

### CODE REVIEW

**Comment by josh18** [comment]
Thanks for the pull request!

I'm getting the error message `Uncaught TypeError: Cannot read property '0' of undefined` from line 4302.
```js
divs = win.$el[0].getElementsByTagName('div');
```
Any ideas?

**Comment by csauthoff** [comment]
Can't reproduce, which version of TinyMCE are you using?
win.$el[0] should hold the window object. Did that only to prevent the subsequent loop to iterate through all div's on the page. 
Did a fix anyway (it now grabs the window object from win._id, if win.$el is not present), could you retry?

**Comment by josh18** [comment]
Thanks it's working now.

I was on TinyMCE 4.1.10 but I upgraded to 4.2.6 and the issue was still happening with the unfixed version. Where is `$el` coming from?

Gonna make a couple of small changes and then I'll commit back here before we merge with master.

**Comment by josh18** [comment]
Hey just letting you know that I decided not to use this pull request as from my experience I found too many bugs when I removed mceNonEditable. I hope you don't mind I have implemented some of your other ideas in a different branch. Thanks for your input!

**Pull request closed without merging**
