### PR TITLE
V5

### PR DESCRIPTION
**Pull request by jsonjuri**
Hi, I've added Font Awesome (Pro) 5.

I didn't add the translations, In Font Awesome 5 the categories are different so the translations still have to be modified.

A good extra feature would be to also switch between light, regular and solid icons.

### CODE REVIEW

**Comment by josh18** [comment]
👍 will merge this and then make some minor changes

**Comment by josh18** [comment]
@jsonjuri do we need to support Font Awesome pro or can we just add support for the free icons? I was hoping to generate the required metadata from https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/metadata/icons.json to make things a bit simpler

**Comment by jsonjuri** [comment]
@josh18 I am not sure, we are using pro in our editor, I think pro also contains all free so you can have 2 in 1. Feel free to change the way you think is best. I have modified it for own use and happy to share it with you so you can easily adjust it for your own publication.

**Comment by josh18** [comment]
Do you know if there is any way to access the pro metadata file?

**Comment by jsonjuri** [comment]
@josh18 I have now added it to my fork in the /assets folder.

Maybe its an idea to make a "var freepro = 'free' // pro" in plugin.js and load the JSON file directly from assets dir like this: https://stackoverflow.com/a/39571547

**Pull request merged**
