### PR TITLE
Adding german, english and spanisch translation for search field and not found message

### PR DESCRIPTION
**Pull request by cliffparnitzky**
Unfortunately, the Russian and Japanese translation are missing.

### CODE REVIEW

**Comment by josh18** [comment]
Sorry, fixed now. Didn't use this branch as I needed to add the other language files as well. Let me know if you find any mistakes.

**Comment by cliffparnitzky** [comment]
Okay, thanks. The german translation for "Close" (https://github.com/josh18/TinyMCE-FontAwesome-Plugin/blob/master/fontawesome/langs/de.js#L19) is "Schließen" or escaped "Schlie\u00dfen".

But this is not absolutely necessary, because its part of the tiny mce core translations. So, you could remove it.

**Comment by josh18** [comment]
Oh you are right, I'll just remove it completely to keep it consistent.

**Comment by cliffparnitzky** [comment]
great, thank you

**Pull request closed without merging**
